from __future__ import annotations

from openscout.models import Journey, RunReport


def generate_playwright_test(journey: Journey, report: RunReport, base_url: str) -> str:
    lines = [
        '"""Generated by OpenScout. Review before committing."""',
        "from playwright.sync_api import Page, expect",
        "",
        "",
        f"def test_{_slug(journey.name)}(page: Page) -> None:",
        f'    page.set_default_timeout(8000)',
    ]
    opened = False
    for step in report.steps:
        if step.status != "passed":
            continue
        action = step.action
        if action.type == "open":
            target = action.target
            if target in {"/", "home", "the demo shop", "demo shop", "the home page", "home page"}:
                target = base_url
            lines.append(f'    page.goto("{target}")')
            opened = True
            continue
        if not opened:
            lines.append(f'    page.goto("{base_url}")')
            opened = True
        if step.locator and action.type == "click":
            lines.append(f"    {step.locator}.click()")
        elif step.locator and action.type == "fill":
            label = step.locator
            if ".fill(" in label:
                lines.append(f"    {label}")
            else:
                lines.append(f'    {label}.fill("{_escape(action.value)}")')
        elif action.type == "see":
            lines.append(f'    expect(page.get_by_text("{_escape(action.target)}")).to_be_visible()')
        elif action.type == "url_contains":
            lines.append(f'    expect(page).to_have_url(re.compile(r"{_escape(action.target)}"))')
        elif action.type == "wait":
            lines.append(f"    page.wait_for_timeout({action.value})")
        elif action.type == "screenshot":
            lines.append(f'    page.screenshot(path="step-{step.index:02d}.png")')
    if not opened:
        lines.append(f'    page.goto("{base_url}")')
    body = "\n".join(lines)
    if "re.compile" in body:
        lines.insert(2, "import re")
        body = "\n".join(lines)
    return body + "\n"


def _slug(name: str) -> str:
    cleaned = "".join(ch.lower() if ch.isalnum() else "_" for ch in name).strip("_")
    while "__" in cleaned:
        cleaned = cleaned.replace("__", "_")
    return cleaned or "journey"


def _escape(value: str) -> str:
    return (value or "").replace("\\", "\\\\").replace('"', '\\"')
